### ISSUE TITLE
Example passing args to run()

### ISSUE THREAD

**Issue by cisaacson** [JXA-userland/JXA#19]
Can you provide an example of how to pass arguments to a `run` function?

We tried this and a few other things:

```
    const g = 'hello ';
    // This function is JXA
    return run((g) => {
        const sys = Application("System Events");
        return g + sys.currentUser().name();
    });
```

The argument just comes in as 'undefined'. 

In a related question, how can we call another defined `function` from within the `run` function?

Great library by the way, very helpful.

**Comment by cisaacson** [comment]
I found the example on the README doc, it just wasn't in the example src. If you want a pull request with another example, we will be happy to do it.

Thanks!

**Comment by castroCrea** [comment]
Hello @cisaacson I can find the solution, can you give an exemple or point to the doc plz.
