### ISSUE TITLE
Need Install Instructions for Visual Studio Code (VSC)

### ISSUE THREAD

**Issue by JMichaelTX** [JXA-userland/JXA#4]
First, thanks for building and sharing a terrific tool!  👍
I can't wait to start using it.

However, I need help.  Can you please provide detailed, step-by-step, instructions on how to install your JXA autocomplete into Visual Studio Code?

Thanks.

**Comment by azu** [comment]
Thanks for feedback.

[@jxa/global-type](https://github.com/JXA-userland/JXA/tree/master/packages/@jxa/global-type)'s approach is same with Cypress that is a E2E framework.

- [Intelligent Code Completion | Cypress Documentation](https://docs.cypress.io/guides/tooling/intelligent-code-completion.html#Set-up-in-your-Dev-Environment)
- [JXA/packages/@jxa/global-type at master · JXA-userland/JXA](https://github.com/JXA-userland/JXA/tree/master/packages/@jxa/global-type)

There are serveral pattern of usage.

### TypeScript user

If you write JXA script as [TypeScript](https://www.typescriptlang.org/) project, you just import `@jxa/global-type`

**file.ts**:
```ts
import("@jxa/global-type");
```

### JavaScript user

If you write JXA as JavaScript, you should do following steps:

1. Create `package.json`
  - `$ npm init --yes` 
2. Install `@jxa/global-type`
  - `$ npm install -D @jxa/global-type`
3. Adding [`tsconfig.json`](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html) file with the following configuration should get intelligent code completion working.

**tsconfig.json:**
```json5
{
  "compilerOptions": {
    "allowJs": true,
    "types": [
      "@jxa/global-type"
    ]
  },
  "include": [
    "**/*.js" // <= this scope is integrated with @jxa/global-type
  ]
}
```

4. Write JXA code as JavaScript like `file.js`

Also, I've created starter repository for JavaScript user.

- [JXA-userland/editor-integrate-example](https://github.com/JXA-userland)

```shell-session
git clone https://github.com/JXA-userland/editor-integrate-example
cd editor-integrate-example
vscode .
```

![image](https://user-images.githubusercontent.com/19714/42131508-322f3ff0-7d3e-11e8-94c0-6895281f6463.png)

**Comment by JMichaelTX** [comment]
Thanks again for all the information you have provided.  
I've tried many things but still can not get autocomplete of my JXA code to work.
Would it be possible to do a screen share some time, where you could walk me through this process?
If you would do that, then I would be happy to create a YouTube video showing users like me how to get this done.

**Comment by vinhquach** [comment]
@azu 
Hi, I installed all packages but couldn't figured it out. 
Could you please be more specific on how to setup for VS Code please?
For example, how to step-by-step setup VS Code for writing a JXA automating Safari or System Events? Which directory should Safari.d.ts go to?
