### ISSUE TITLE
Put types into DefinitelyTyped

### ISSUE THREAD

**Issue by beizhedenglong** [JXA-userland/JXA#9]
Hi @azu, can you put `types` into [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)?

**Comment by azu** [comment]
Why?
[DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) handle a typing for existing npm package.
[@jxa/types](https://github.com/JXA-userland/JXA/tree/master/packages/%40jxa/types) is not the case.
You can use [@jxa/types](https://github.com/JXA-userland/JXA/tree/master/packages/%40jxa/types) by installing `npm install @jxa/types`.
